from .board import BoardTemplate
from .chassis import ChassisTemplate
from .enthernet_interface import EthernetInterfaceTemplate
from .fan import FanTemplate
from .manager import ManagerTemplate
from .memory import MemoryTemplate
from .other import OtherTemplate
from .pcie import PCIeTemplate
from .port import PortTemplate
from .power import PowerTemplate
from .processor import ProcessorTemplate
from .raid import RAIDTemplate
from .server import ServerTemplate
from .storage import StorageTemplate
from .switch import SwitchTemplate
